### ISSUE TITLE
Stop stealing

### ISSUE THREAD

**Issue by Ujjwalm2004** [santosharron/ai-art#1]
Hello Bro this the code of VikramadityaDev- text_to_image_gen why are you stealing his code if you want to make your own app then pls give credits or else we will make our all projects privet and you will never get any updates 

Pls Give credits 🥲

**Comment by santosharron** [comment]
I'm really sorry if there was any confusion about the code. I never intended to steal or copy VikramadityaDev's work. I mentioned their code because it inspired me for my own project.

I understand how important it is to give credit where it's due, and I totally appreciate VikramadityaDev's hard work. If there are specific parts of their code that I used, I'll definitely make sure to give them proper credit.

I'm just trying to create my own app while using some existing ideas and techniques. I really value the collaboration and respect among developers, and I want to make sure I'm doing the right thing.
